<a href="https://colab.research.google.com/github/jonathonkischuk/AI/blob/main/basic_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils._bunch.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
X = iris.data

In [7]:
y = iris.target

In [8]:
# class 0 --> [1,0,0]
# class 1 --> [0,1,0]
# class 2 --> [0,0,1]

In [9]:
from keras.utils import to_categorical

In [10]:
y = to_categorical(y)

In [11]:
y.shape

(150, 3)

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [15]:
scaler_obj = MinMaxScaler()

In [16]:
scaler_obj.fit(X_train)

MinMaxScaler()

In [17]:
scaled_X_train = scaler_obj.transform(X_train)

In [18]:
scaled_X_test = scaler_obj.transform(X_test)

In [19]:
# scaled_X_train

In [20]:
from keras.models import Sequential
from keras.layers import Dense

In [21]:
model = Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam', metrics=['accuracy'])

In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139 (556.00 Byte)
Trainable params: 139 (556.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [23]:
model.fit(scaled_X_train,y_train,epochs=150,verbose=2)

Epoch 1/150
4/4 - 4s - loss: 1.2731 - accuracy: 0.3500 - 4s/epoch - 880ms/step
Epoch 2/150
4/4 - 0s - loss: 1.2528 - accuracy: 0.3500 - 67ms/epoch - 17ms/step
Epoch 3/150
4/4 - 0s - loss: 1.2332 - accuracy: 0.3500 - 51ms/epoch - 13ms/step
Epoch 4/150
4/4 - 0s - loss: 1.2178 - accuracy: 0.3500 - 39ms/epoch - 10ms/step
Epoch 5/150
4/4 - 0s - loss: 1.2025 - accuracy: 0.3500 - 33ms/epoch - 8ms/step
Epoch 6/150
4/4 - 0s - loss: 1.1894 - accuracy: 0.3700 - 27ms/epoch - 7ms/step
Epoch 7/150
4/4 - 0s - loss: 1.1770 - accuracy: 0.3700 - 24ms/epoch - 6ms/step
Epoch 8/150
4/4 - 0s - loss: 1.1665 - accuracy: 0.3800 - 46ms/epoch - 12ms/step
Epoch 9/150
4/4 - 0s - loss: 1.1563 - accuracy: 0.4200 - 40ms/epoch - 10ms/step
Epoch 10/150
4/4 - 0s - loss: 1.1458 - accuracy: 0.4900 - 39ms/epoch - 10ms/step
Epoch 11/150
4/4 - 0s - loss: 1.1348 - accuracy: 0.5600 - 33ms/epoch - 8ms/step
Epoch 12/150
4/4 - 0s - loss: 1.1251 - accuracy: 0.6300 - 29ms/epoch - 7ms/step
Epoch 13/150
4/4 - 0s - loss: 1.1166 - accu

In [24]:
model.predict(scaled_X_test)

2/2 [==============================] - 0s 6ms/step


array([[0.0577789 , 0.41671193, 0.5255091 ],
       [0.9206637 , 0.05334355, 0.02599264],
       [0.00681482, 0.3631103 , 0.63007486],
       [0.06790175, 0.4106669 , 0.5214313 ],
       [0.02991578, 0.37697756, 0.59310657],
       [0.87848324, 0.07921893, 0.04229783],
       [0.18935066, 0.40209934, 0.40855008],
       [0.01726375, 0.33603066, 0.6467056 ],
       [0.03574274, 0.41923547, 0.5450217 ],
       [0.10449272, 0.41681993, 0.4786874 ],
       [0.03529681, 0.37856016, 0.586143  ],
       [0.8749635 , 0.08401007, 0.04102644],
       [0.9170593 , 0.05560522, 0.02733545],
       [0.8821973 , 0.07947545, 0.03832722],
       [0.9445949 , 0.03866288, 0.01674224],
       [0.09128451, 0.40807933, 0.50063616],
       [0.01736275, 0.36414832, 0.618489  ],
       [0.09096355, 0.42398044, 0.48505607],
       [0.08248381, 0.4265141 , 0.49100214],
       [0.01849035, 0.36739075, 0.6141188 ],
       [0.8941773 , 0.07231873, 0.03350396],
       [0.04472568, 0.39758533, 0.5576891 ],
       [0.

In [25]:
# predictions = model.predict_classes(scaled_X_test)

predictions = np.argmax(model.predict(scaled_X_test),axis=1)

2/2 [==============================] - 0s 10ms/step


In [26]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [27]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [28]:
confusion_matrix(y_test.argmax(axis=1),predictions)

array([[19,  0,  0],
       [ 0,  0, 15],
       [ 0,  0, 16]])

In [29]:
print(classification_report(y_test.argmax(axis=1),predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.00      0.00      0.00        15
           2       0.52      1.00      0.68        16

    accuracy                           0.70        50
   macro avg       0.51      0.67      0.56        50
weighted avg       0.55      0.70      0.60        50



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [30]:
accuracy_score(y_test.argmax(axis=1),predictions)

0.7

In [31]:
model.save('myfirstmodel.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [32]:
from keras.models import load_model

In [33]:
new_model = load_model('myfirstmodel.h5')